- name: Install php-fpm
  ansible.builtin.apt:
    name: php8.1-fpm
    state: latest
    update_cache: yes
- name: Copy php-fpm config file
  ansible.builtin.template:
    src: test.conf.j2
    dest: /etc/php/8.1/fpm/pool.d/test.conf
    owner: root
    group: root
    mode: '0644'
- name: Restart php-fpm
  ansible.builtin.service:
    name: php8.1-fpm
    state: restarted